import Navbar from "@/components/Navbarcomponets/Nav";
import "./globals.css";
import { NextuiProviderWrapper } from "./provider";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footercomponets/Footer";
import Topfooter from "@/components/Footercomponets/Topfooter";
import { Providers } from "@/lib/Redux/provider";

const inter = Roboto({
  weight: ["100", "400", "300", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <NextuiProviderWrapper>
            {children}
          </NextuiProviderWrapper>
        </body>
      </html>
    </Providers>
  );
}
