import "./globals.css";
import { NextuiProviderWrapper } from "./provider";
import { Roboto } from "next/font/google";
import { Providers } from "@/lib/Redux/provider";
import Script from 'next/script';
import { Toaster } from "@/components/ui/toaster";


const inter = Roboto({
  weight: ["100", "400", "300", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <Providers>
      <html lang="en">
      <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />
        <body className={inter.className}>
          <NextuiProviderWrapper>
            {children}
            <Toaster />
          </NextuiProviderWrapper>
        </body>
      </html>
    </Providers>
  );
}
